# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:14.17-browsers

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
        version: 20.10.7
      -run:
        name: Build Docker Image
        command: docker build -t myapp -f Dockerfile.dev .
      - run:
        command: docker run -t myapp npm run test -- --coverage
